# Generated by Django 4.2.2 on 2023-07-02 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_commentgood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentgood',
            old_name='post',
            new_name='comment',
        ),
    ]
